# hotel-customer cluster
---
kind: Service
apiVersion: v1
metadata:
  name: hotel-customer
  labels:
    app: hotel-customer
spec:
  selector:
    app: hotel-customer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
data:
  application-kube.yml: |-
    server:
      port: 80
    logging:
      config: classpath:env/prod/logback.xml      
    spring:
      application:
        name: wkxhotel-file
      jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        joda-date-time-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
      jmx:
        enabled: false

    #########fastdfs###########
    fdfs:
      thumb-image:
        height: 150
        width: 150
      soTimeout: 50
      connectTimeout: 2
      trackerList: 192.168.50.4:22125
    #########imgUrl############
    fastdfs: 
      img-url: http://s1.veimg.cn/meadin/

    #########eureka############
    eureka:
      instance:
        preferIpAddress: true
      client:
        registerWithEureka: true
        service-url:
          defaultZone: http://admin:123456@eureka-0.eureka:80/eureka/,http://admin:123456@eureka-1.eureka:80/eureka/,http://admin:123456@eureka-2.eureka:80/eureka/

kind: ConfigMap
metadata:
  name: hotel-customerconfig
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hotel-customer
  labels:
    app: hotel-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-customer
  template:
    metadata:
      labels:
        app: hotel-customer
    spec:
      containers:
      - name: hotel-customer
        image: docker-registry.cluster.dfwsgroup.cn/library/wkxhotel-web-customer:1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "300Mi"
            cpu: "250m"
          limits:
            memory: "2000Mi"
            cpu: "2000m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: hotel-customer-config
          mountPath: /config
      volumes:
      - name: hotel-customer-config
        configMap:
          name: hotel-customerconfig
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hotel-gateway
  annotations:
    #kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  #tls:
  #- hosts:
  #  - hotel-waiter.cluster.dfwsgroup.cn
  #  secretName: hotel-waiter-tls
  rules:
  - host: hotel-customer.cluster.dfwsgroup.cn
    http:
      paths:
      - path: /
        backend:
          serviceName: hotel-customer
          servicePort: 80