# hotel-job cluster
---
kind: Service
apiVersion: v1
metadata:
  name: hotel-job
  labels:
    app: hotel-job
spec:
  selector:
    app: hotel-job
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30787
  type: NodePort
---
apiVersion: v1
data:
  application-kube.yml: |-
    server:
      port: 80
    logging:
      config: classpath:env/prod/logback.xml      
    spring:
      jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
      application:
        name: wkxhotel-service-job
    #########xxl############     
    xxl:
      job:
        admin:
          addresses: http://job.wkxhotel.com
        executor: 
          appname: wkxhotel-service-job
          ip: 192.168.50.57
          port: 30787
          logpath: /tmp/
        accessToken:
    #########ribbon############
    ribbon:
      eureka:
        enabled: true
      ReadTimeout: 30000
      ConnectTimeout: 30000
      MaxAutoRetries: 0
      MaxAutoRetriesNextServer: 1
      OkToRetryOnAllOperations: false  
    #########eureka############
    eureka:
      instance:
        preferIpAddress: true
      client:
        registerWithEureka: true
        service-url:
          defaultZone: http://admin:123456@eureka-0.eureka:80/eureka/,http://admin:123456@eureka-1.eureka:80/eureka/,http://admin:123456@eureka-2.eureka:80/eureka/

kind: ConfigMap
metadata:
  name: hotel-jobconfig
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hotel-job
  labels:
    app: hotel-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-job
  template:
    metadata:
      labels:
        app: hotel-job
    spec:
      containers:
      - name: hotel-job
        image: docker-registry.cluster.dfwsgroup.cn/library/wkxhotel-service-job:1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "300Mi"
            cpu: "250m"
          limits:
            memory: "2000Mi"
            cpu: "2000m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: hotel-job-config
          mountPath: /config
      volumes:
      - name: hotel-job-config
        configMap:
          name: hotel-jobconfig

